### ISSUE TITLE
installing suggestions

### ISSUE THREAD

**Issue by harlet** [mpociot/documentarian#2]
Hi, i have this errors:

windwalker/renderer suggests installing league/plates (Install 3.* if you require Plates template engine.)
windwalker/renderer suggests installing twig/twig (Install 1.* if you require Twig engine.)
windwalker/renderer suggests installing mustache/mustache (Install 2.* if you require Mustache engine.)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
illuminate/support suggests installing symfony/process (Required to use the composer class (3.1.*).)
illuminate/support suggests installing symfony/var-dumper (Required to use the dd function (3.1.*).)
illuminate/filesystem suggests installing league/flysystem (Required to use the Flysystem local and FTP drivers (~1.0).)
illuminate/filesystem suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
illuminate/filesystem suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/process ()

**Comment by mpociot** [comment]
Hey,

these are not errors. Composer is just telling you that the specified packages _suggest_ that you install other packages.

It's in no way required.
