### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by Tellurian7** [mpociot/documentarian#4]
Hi,

I need more informations on the Documentarian syntax but the links are broken (http://marcelpociot.com/documentarian/installation is down)

**Comment by mpociot** [comment]
Yeah - I know. I'm having some problems with the domain registrar.
Please use http://marcelpociot.de/documentarian/installation in the meantime

**Comment by menkaff** [comment]
Hi @mpociot thanks for your awesome packages , this package documentation redirect to this 404 page  [https://pociot.dev/documentarian/installation](url)
