### ISSUE TITLE
rules exists:table,id check value for example

### ISSUE THREAD

**Issue by veneliniliev** [mpociot/documentarian#5]
rule:
` 'collection_country_id' => 'integer|exists:countries,id',`

documentation row:
`collection_country_id	integer	optional	Valid country id`

example request:
` -d "collection_country_id"="4166" \`

i dont have country id = 4166

**Comment by mpociot** [comment]
This issue is not related to documentarian but to [Laravel API Doc Generator](https://github.com/mpociot/laravel-apidoc-generator).
The example requests only contain randomly seeded data - in this case a random integer.
